// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"accessToken"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Mobile   string `json:"mobile"`
	Gender   string `json:"gender,options=male|female|unknown"`
	Nickname string `json:"nickname"`
}

type RegisterResp struct {
	Result string `json:"result"`
}
