// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	group1 "go-zero/doing/api/user/internal/handler/group1"
	"go-zero/doing/api/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: group1.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: group1.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)
}
