// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go_zero/demo/demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/sign-up",
				Handler: UserSignUpHandler(serverCtx),
			},
		},
	)
}
